import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./auth-provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-b from-blue-200 to-white w-full"
      >
        <AuthProvider >{children} </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
